export const ProductList = [
  {
    id: 1,
    image: "/image/honey.png",
    title: "Goraw Honey",
    price: "1080",
    badgeFeatured: "Featured",
    badgeBestSelling: "Best Selling",
  },
  {
    id: 2,
    image: "/image/honey-product.webp",
    title: "Trueney Raw Honey",
    price: "2090",
    badgeTopSeller: "Top Seller",
    badgeBestSelling: "Best Selling",
  },
  {
    id: 3,
    image: "/image/honey-product.webp",
    title: "Organic Raw Honey",
    price: "3090",
    badgeTopSeller: "Top Seller",
    badgeFeatured: "Featured",
  },
  {
    id: 4,
    image: "/image/honey-product.webp",
    title: "Organic Raw Honey",
    price: "3090",
    badgeTopSeller: "Top Seller",
    badgeFeatured: "Featured",
  },
  {
    id: 5,
    image: "/image/honey-product.webp",
    title: "Organic Raw Honey",
    price: "3090",
    badgeTopSeller: "Top Seller",
    badgeFeatured: "Featured",
  },
];
